on: push 
jobs:
    print-version:
        runs-on: windows-latest
        steps: 
              - run: node --version
              - run: npm --version
              - uses: actions/checkout@v3
              - run: node index.js